In [340]:
from sklearn.datasets import fetch_openml

# Load Titanic from OpenML via scikit-learn as a single DataFrame
df = fetch_openml("titanic", version=1, as_frame=True).frame.copy()

print(df.shape)

(1309, 14)

In [341]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [342]:
df.tail()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [343]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [344]:
df.dtypes

pclass          int64
survived     category
name           object
sex          category
age           float64
sibsp           int64
parch           int64
ticket         object
fare          float64
cabin          object
embarked     category
boat           object
body          float64
home.dest      object
dtype: object

In [345]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   category
 2   name       1309 non-null   object
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   category
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: category(3), float64(3), int64(3), object(5)
memory usage: 116.8+ KB

In [346]:
df.describe()

,pclass,age,sibsp,parch,fare,body
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [347]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [348]:
missing_pct = (df.isnull().sum() / len(df)) * 100
print(missing_pct)

pclass        0.000000
survived      0.000000
name          0.000000
sex           0.000000
age          20.091673
sibsp         0.000000
parch         0.000000
ticket        0.000000
fare          0.076394
cabin        77.463713
embarked      0.152788
boat         62.872422
body         90.756303
home.dest    43.086325
dtype: float64

In [349]:
print(missing_pct.sort_values(ascending=False))

body         90.756303
cabin        77.463713
boat         62.872422
home.dest    43.086325
age          20.091673
embarked      0.152788
fare          0.076394
sibsp         0.000000
name          0.000000
survived      0.000000
pclass        0.000000
sex           0.000000
parch         0.000000
ticket        0.000000
dtype: float64

In [350]:
df["age"]

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [351]:
df[["age", "sex", "survived"]]

          age     sex survived
0     29.0000  female        1
1      0.9167    male        1
2      2.0000  female        0
3     30.0000    male        0
4     25.0000  female        0
...       ...     ...      ...
1304  14.5000  female        0
1305      NaN  female        0
1306  26.5000    male        0
1307  27.0000    male        0
1308  29.0000    male        0

[1309 rows x 3 columns]

In [352]:
df[df["age"] > 50].describe()

          pclass        age      sibsp      parch        fare        body
count  95.000000  95.000000  95.000000  95.000000   94.000000   19.000000
mean    1.442105  58.731579   0.378947   0.368421   61.366313  173.368421
std     0.695208   6.099272   0.549254   0.812831   74.755585   92.309390
min     1.000000  51.000000   0.000000   0.000000    6.237500   19.000000
25%     1.000000  54.000000   0.000000   0.000000   17.750000  109.000000
50%     1.000000  58.000000   0.000000   0.000000   31.508300  175.000000
75%     2.000000  62.000000   1.000000   0.000000   78.189600  253.500000
max     3.000000  80.000000   2.000000   4.000000  512.329200  307.000000

In [353]:
df_female = df[df["sex"] == "female"]
df_female["sex"].value_counts()

sex
female    466
male        0
Name: count, dtype: int64

In [354]:
df_firstclass_female = df[
    (df["sex"] == "female") &
    (df["pclass"] == 1)
]
df_firstclass_female["pclass"].value_counts()

pclass
1    144
Name: count, dtype: int64

In [355]:
df["age"] = df["age"].fillna(df["age"].median())
df["age"].isnull().sum()

np.int64(0)