# Joint Probability

This notebook explains **joint probability**, which is the probability of two or more events happening at the same time. We will use a single, consistent example to explore how to define, compute, and interpret it.

## What is Joint Probability?

The joint probability of two events, A and B, is the probability that they both occur. It is denoted as $P(A \cap B)$ or $P(A, B)$.

When working with two random variables, $X$ and $Y$, the joint probability is the probability that $X$ takes a specific value $x_i$ and $Y$ takes a specific value $y_j$.

$P(X = x_i, Y = y_j)$

We can estimate this from data by counting how many times both outcomes occurred together and dividing by the total number of trials.

$P(X = x_i, Y = y_j) = \frac{\text{Number of times } (X=x_i \text{ and } Y=y_j)}{\text{Total number of trials}}$

## The Joint Probability Distribution

The **joint probability distribution** of two discrete random variables, $X$ and $Y$, is the collection of all possible joint probabilities $P(X=x_i, Y=y_j)$. It is often represented as a table.

The sum of all probabilities in a joint distribution must equal 1.

$\sum_{i} \sum_{j} P(X = x_i, Y = y_j) = 1$

## Example: Colored Shapes

Consider a box of 100 objects with different colors and shapes.
- **Random Variable X (Color):** Can be Red (R), Green (G), or Blue (B).
- **Random Variable Y (Shape):** Can be Sphere (S) or Cube (C).

The counts of each combination are as follows:
- Red Sphere: 18
- Green Sphere: 12
- Blue Sphere: 30
- Red Cube: 16
- Green Cube: 20
- Blue Cube: 4

We can represent these counts and the corresponding joint probabilities in a table.

In [ ]:
import pandas as pd

# Rows: Y values (S, C), Columns: X values (R, G, B)
counts = pd.DataFrame(
    [[18, 12, 30],
     [16, 20, 4]],
    index=['Shape=S', 'Shape=C'],
    columns=['Color=R', 'Color=G', 'Color=B']
 )

total_count = int(counts.values.sum())
joint_probabilities = counts / total_count

print(f'Total objects = {total_count}')
print('\\n--- Counts Table ---')
display(counts)
print('\\n--- Joint Probability Table P(X, Y) ---')
display(joint_probabilities)

# Example calculation
p_red_sphere = joint_probabilities.loc['Shape=S', 'Color=R']
print(f"\\nExample: P(Color=R, Shape=S) = {counts.loc['Shape=S', 'Color=R']}/{total_count} = {p_red_sphere:.2f}")

# Verify that the sum is 1
print(f"\\nSum of all joint probabilities = {joint_probabilities.values.sum():.2f}")

Total objects N_s = 100
Counts table:

     X=R  X=G  X=B
Y=S   18   12   30
Y=C   16   20    4

Joint probability table P(X, Y):

      X=R   X=G   X=B
Y=S  0.18  0.12  0.30
Y=C  0.16  0.20  0.04

Individual joint probabilities:
P(X=R, Y=S) = 18/100 = 0.18
P(X=R, Y=C) = 16/100 = 0.16
P(X=G, Y=S) = 12/100 = 0.12
P(X=G, Y=C) = 20/100 = 0.20
P(X=B, Y=S) = 30/100 = 0.30
P(X=B, Y=C) = 4/100 = 0.04
Sum of all joint probabilities = 1.00

## Summary

- **Joint Probability** $P(A, B)$ is the probability of events A and B both happening.
- A **Joint Probability Distribution** lists all possible joint probabilities for two or more random variables.
- The sum of all probabilities in a joint distribution is always 1.
- Joint probability tables are a fundamental tool for working with multiple random variables in machine learning.